[pytest]
testpaths = ./test_cases/
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --alluredir=./reports/allure-results --clean-alluredir


markers =
    smoke: 冒烟测试，核心接口快速验证
    user: 用户模块用例
    order: 订单模块用例
    dev: 开发环境专用用例
    slow: 执行耗时较长的用例
